### ISSUE TITLE
Consider an optional rule mode for this plugin?

### ISSUE THREAD

**Issue by getify** [arendjr/eslint-plugin-no-pipe#1]
I agree mostly with the spirit of this plugin. I dislike how `|>` has been designed (and intentionally limited). But I wonder if there aren't some *small* exceptions where `|>` might have a bit of merit?

I am curious if you would consider/accept adding an optional (off by default) mode/rule for this plugin, where it doesn't outright disallow `|>`, but specifically disallows:

* any usage where the topic is bound to preceding simple literal, identifier, or property reference is bound as the topic
* any usage where the topic (`%`, `^`, `^^`, or whatever the heck they pick) is used *not* inside an argument to a call expression

Such a mode would still error on all these absurdities:

```js
42 |> [ 1, 2, % ]

"Hello world" |> console.log(%)

func |> %(42)

tagFn |> %`whatever`

cb |> pr.then(%)

obj.increment |> arr.map(%)

tagFn |> %`whatever`
```

But the mode would still allow some `|>` usage, like these:

```js
fortyTwo() | [ 1, 2 ].concat(%)

"Hello world".toUpperCase() |> console.log(%)

(obj.increment ?? identity) |> arr.map(%)
```

The thinking behind allowing those is:

1. functional composition is still a valid use-case
2. a complex expression in an argument position of a function call *can be* rather unreadable, so there's potentially *some slight* benefit in separating the expression from the call-site with the `|>`.

What do you think?

**Comment by arendjr** [comment]
I’m not entirely against the suggestion, but I do think I would tighten things even more as I think the examples of what *is* allowed here to still not be very convincing. Personally I would still disallow all three of these examples, but I can understand not everybody feels as strict as I do.

As such, I would be open to the contribution of a more relaxed rule, and I think your suggestions are a good start. Some options I would personally add are:

* `minPipelineLength`: Only allow the operator if you’re piping through at least a certain amount of invocations (I believe `2` to be a good default)
* `tacitFunctionsOnly` to limit the right-hand side to tacit functions only (so no method calls)
* `unaryFunctionsOnly` to limit the right-hand side to functions that only accept a single argument (so no mixing of the topic token with other arguments)

Don’t feel obligated to implement all of these if you want to contribute a PR (though it would be appreciated!). Just sharing my thoughts :)
